package com.focusmother.android.data.dao

import android.content.Context
import androidx.arch.core.executor.testing.InstantTaskExecutorRule
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.focusmother.android.data.database.FocusMotherDatabase
import com.focusmother.android.data.entity.Agreement
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class AgreementDaoTest {

    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()

    private lateinit var database: FocusMotherDatabase
    private lateinit var agreementDao: AgreementDao

    @Before
    fun setup() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, FocusMotherDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        agreementDao = database.agreementDao()
    }

    @After
    fun teardown() {
        database.close()
    }

    @Test
    fun insert_agreementWithAutoGeneratedId_returnsValidId() = runTest {
        val agreement = Agreement.create(
            appPackageName = "com.instagram.android",
            appName = "Instagram",
            appCategory = "SOCIAL_MEDIA",
            agreedDurationMs = 30 * 60 * 1000L,
            conversationId = 1L
        )
        val insertedId = agreementDao.insert(agreement)
        assertTrue("Inserted ID should be positive", insertedId > 0)
    }

    @Test
    fun getById_existingAgreement_returnsAgreement() = runTest {
        val agreement = Agreement.create(
            appPackageName = "com.instagram.android",
            appName = "Instagram",
            appCategory = "SOCIAL_MEDIA",
            agreedDurationMs = 30 * 60 * 1000L,
            conversationId = 1L
        )
        val id = agreementDao.insert(agreement)
        val retrieved = agreementDao.getById(id)
        assertNotNull("Agreement should be found", retrieved)
        assertEquals("ID should match", id, retrieved?.id)
    }

    @Test
    fun getByStatus_activeAgreements_returnsOnlyActive() = runTest {
        val activeAgreement = Agreement.create(
            appPackageName = "com.instagram.android",
            appName = "Instagram",
            appCategory = "SOCIAL_MEDIA",
            agreedDurationMs = 30 * 60 * 1000L,
            conversationId = 1L
        )
        agreementDao.insert(activeAgreement)
        val activeAgreements = agreementDao.getByStatus(Agreement.STATUS_ACTIVE)
        assertEquals("Should return active agreement", 1, activeAgreements.size)
    }

    @Test
    fun markViolated_agreement_setsStatusAndTimestamp() = runTest {
        val agreement = Agreement.create(
            appPackageName = "com.instagram.android",
            appName = "Instagram",
            appCategory = "SOCIAL_MEDIA",
            agreedDurationMs = 30 * 60 * 1000L,
            conversationId = 1L
        )
        val id = agreementDao.insert(agreement)
        val violatedTime = System.currentTimeMillis()
        agreementDao.markViolated(id, violatedTime)
        val updated = agreementDao.getById(id)
        assertEquals("Status should be VIOLATED", Agreement.STATUS_VIOLATED, updated?.status)
        assertEquals("Violated time should be set", violatedTime, updated?.violatedAt)
    }

    @Test
    fun deleteAll_removesAllAgreements() = runTest {
        val agreement = Agreement.create(
            appPackageName = "com.instagram.android",
            appName = "Instagram",
            appCategory = "SOCIAL_MEDIA",
            agreedDurationMs = 30 * 60 * 1000L,
            conversationId = 1L
        )
        agreementDao.insert(agreement)
        agreementDao.deleteAll()
        val agreements = agreementDao.getAll()
        assertTrue("Database should be empty", agreements.isEmpty())
    }
}
